import numpy as np
from .fk import *
from .se3 import *
from .jacobian import *
from .poe import *
from typing import Callable


def finite_difference_grad(w_func, theta, eps=1e-6):
    """
    Note: This function is generated by AI.

    Computes:
        ∂w/∂θ_i ≈ (w(θ + ε e_i) - w(θ - ε e_i)) / (2ε)
        where e_i is the unit vector along the i-th coordinate.

    Inputs:
        w_func : objective function that takes (n,) array_like theta and returns a scalar w
        theta : (n,) joint coordinates
        eps : Finite difference step size (default: 1e-6).

    Returns:
        grad : (n,) Approximate gradient vector ∇w(theta).
    """
    grad = np.zeros_like(theta)

    for i in range(len(theta)):
        t1 = theta.copy()
        t2 = theta.copy()

        t1[i] += eps
        t2[i] -= eps

        grad[i] = (w_func(t1) - w_func(t2)) / (2 * eps)

    return grad


def numerical_inverse_kinematics_position(
    M_ee: np.ndarray,
    B_list: list,
    theta_init: np.ndarray,
    p_des: np.ndarray,
    max_iters: int = 100,
    tol_converge: float = 1e-6,
    tol_manipulability: float = 1e-3,
    q_min: np.ndarray | None = None,
    q_max: np.ndarray | None = None,
    objective_func: Callable | None = None,
    objective_args: dict | None = None,
    k_null: float = 0.1,
    k_damping: float = 0.01,
    print_iterations: bool = True,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Computes:
        Numerical IK for end-effector position using the body Jacobian and pseudo-inverse.

    Inputs:
        M_ee : (4x4) home configuration of the end-effector
        B_list : list of (6,) screw axes in the body frame
        theta_init : (n,) initial joint coordinates
        p_des : (3,) desired end-effector position
        max_iters : maximum number of iterations
        tol_converge : convergence tolerance for the end-effector position error
        tol_manipulability : minimum manipulability threshold to consider the solution valid (optional)
        q_min : (n,) minimum joint limits (optional)
        q_max : (n,) maximum joint limits (optional)
        objective_func : function that takes (n,) theta and returns a scalar value (optional)
        objective_args : dictionary of additional arguments to pass to objective_func (optional)
        k_null : weight for the null-space objective (default: 0.1)
        k_damping : damping factor for damped least squares inverse (default: 0.01)
        print_iterations : whether to print iteration details (optional)

    Returns:
        theta : (n,) solution joint coordinates
        theta_history : (max_iters+1, n) history of joint coordinates during iterations
    """
    theta = np.asarray(theta_init, dtype=float).reshape(-1)
    p_des = np.asarray(p_des, dtype=float).reshape(3)

    theta_history = [theta.copy()]

    for i in range(max_iters):

        T_ee = body_product_of_exponentials(M_ee, B_list, theta)
        p_ee = T_ee[:3, 3]

        error = p_des - p_ee

        if print_iterations:
            theta_str = ", ".join(
                f"θ{j+1}={np.degrees(t):.2f}°" for j, t in enumerate(theta)
            )
            print(
                f"Iteration {i}: ({theta_str}), "
                f"(x,y,z)=({p_ee[0]:.3f}, {p_ee[1]:.3f}, {p_ee[2]:.3f}), "
                f"||error||={np.linalg.norm(error):.3e}"
            )

        if np.linalg.norm(error) < tol_converge:
            break

        J_b = body_jacobian(B_list, theta)
        J_v = J_b[3:, :]
        if tol_manipulability < manipulability(J_v):
            J_dagger = pseudoinverse_jacobian(J_v)
        else:
            J_dagger = damped_least_square_inverse(J_v, k=k_damping)

        # primary IK objective: minimize position error
        dq = J_dagger @ error

        # secondary objective: maximize criteria
        if objective_func is not None:
            P = np.eye(len(theta)) - J_dagger @ J_v
            w_func = lambda th: objective_func(th, **objective_args)
            dot_q_0 = k_null * finite_difference_grad(w_func, theta)
            dq += P @ dot_q_0

        theta = theta + dq
        if q_min is not None and q_max is not None:
            theta = np.clip(theta, q_min, q_max)

        theta_history.append(theta.copy())

    return theta, np.array(theta_history)


def numerical_inverse_kinematics_pose(
    M_ee: np.ndarray,
    B_list: list,
    theta_init: np.ndarray,
    T_sd: np.ndarray,
    max_iters: int = 100,
    tol_w: float = 1e-6,
    tol_v: float = 1e-6,
    tol_manipulability: float = 1e-3,
    q_min: np.ndarray | None = None,
    q_max: np.ndarray | None = None,
    objective_func: Callable | None = None,
    objective_args: dict | None = None,
    k_null: float = 0.1,
    k_damping: float = 0.01,
    print_iterations: bool = True,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Computes:
        Numerical IK for end-effector pose using the body Jacobian and pseudo-inverse.

    Inputs:
        M_ee : (4x4) home configuration of the end-effector
        B_list : list of (6,) screw axes in the body frame
        theta_init : (n,) initial joint coordinates
        T_sd : (4x4) desired end-effector pose
        max_iters : maximum number of iterations
        tol_w : convergence tolerance for the end-effector orientation error
        tol_v : convergence tolerance for the end-effector position error
        tol_manipulability : minimum manipulability threshold to consider the solution valid (optional)
        q_min : (n,) minimum joint limits (optional)
        q_max : (n,) maximum joint limits (optional)
        objective_func : function that takes (n,) theta and returns a scalar value (optional)
        objective_args : dictionary of additional arguments to pass to objective_func (optional)
        k_null : weight for the null-space objective (default: 0.1)
        k_damping : damping factor for damped least squares inverse (default: 0.01)
        print_iterations : whether to print iteration details (optional)

    Returns:
        theta : (n,) solution joint coordinates
        theta_history : (max_iters+1, n) history of joint coordinates during iterations
    """
    theta = theta_init.copy()
    theta_history = [theta.copy()]

    for i in range(max_iters):

        T_sb = body_product_of_exponentials(M_ee, B_list, theta)
        T_bs = inv_SE3(T_sb)

        T_bd = T_bs @ T_sd

        S, th = log_screw_axis(T_bd)
        V_b = S * th

        w_b = V_b[:3]
        v_b = V_b[3:]

        theta_deg = np.degrees(theta)

        if print_iterations:
            theta_str = ", ".join(
                f"θ{j+1}={angle:.2f}°" for j, angle in enumerate(theta_deg)
            )
            print(
                f"Iteration {i}: ({theta_str}), "
                f"(x, y, z)=({T_sb[0,3]:.3f}, {T_sb[1,3]:.3f}, {T_sb[2,3]:.3f}), "
                f"||w_b||={np.linalg.norm(w_b):.3f}, "
                f"||v_b||={np.linalg.norm(v_b):.3f}"
            )

        if np.linalg.norm(w_b) <= tol_w and np.linalg.norm(v_b) <= tol_v:
            break

        J_b = body_jacobian(B_list, theta)
        J_dagger = pseudoinverse_jacobian(J_b)

        if tol_manipulability < manipulability(J_b):
            J_dagger = pseudoinverse_jacobian(J_b)
        else:
            J_dagger = damped_least_square_inverse(J_b, k=k_damping)

        # primary IK objective: minimize position error
        dq = J_dagger @ V_b

        # secondary objective: maximize criteria
        if objective_func is not None:
            P = np.eye(len(theta)) - J_dagger @ J_b
            w_func = lambda th: objective_func(th, **objective_args)
            dot_q_0 = k_null * finite_difference_grad(w_func, theta)
            dq += P @ dot_q_0

        theta = theta + dq

        if q_min is not None and q_max is not None:
            theta = np.clip(theta, q_min, q_max)

        theta_history.append(theta.copy())

    return theta, np.array(theta_history)


def manipulability_objective(theta: np.ndarray, B_list: list) -> float:
    """
    Computes:
        w = sqrt(det(J @ J^T))
        J = body_jacobian(B_list, theta)

    Inputs:
        theta : (n,) joint coordinates
        B_list : list of (6,) screw axes in the body frame

    Returns:
        w : manipulability measure
    """
    J = body_jacobian(B_list, theta)
    w = manipulability(J)
    return w


def joint_limit_objective(
    theta: np.ndarray, q_min: np.ndarray, q_max: np.ndarray
) -> float:
    """
    Computes:
        w = -0.5 * sum(((theta - q_bar) / (q_max - q_min)) ** 2) / n
        where q_bar = (q_min + q_max) / 2

    Inputs:
        theta : (n,) current joint coordinates
        q_min : (n,) minimum joint limits
        q_max : (n,) maximum joint limits

    Returns:
        w: distance from joint limits
    """
    span = q_max - q_min
    q_bar = (q_min + q_max) / 2
    w = -0.5 * np.mean(((theta - q_bar) / span) ** 2)
    return w


def ik_jacobian_transpose_position(
    M_ee: np.ndarray,
    B_list: list,
    theta_init: np.ndarray,
    p_des: np.ndarray,
    max_iters: int = 100,
    tol_converge: float = 1e-6,
    q_min: np.ndarray | None = None,
    q_max: np.ndarray | None = None,
    K: np.ndarray = np.eye(3),
    print_iterations: bool = True,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Computes:
        Numerical IK for end-effector position using the body Jacobian and pseudo-inverse.

    Inputs:
        M_ee : (4x4) home configuration of the end-effector
        B_list : list of (6,) screw axes in the body frame
        theta_init : (n,) initial joint coordinates
        p_des : (3,) desired end-effector position
        max_iters : maximum number of iterations
        tol_converge : convergence tolerance for the end-effector position error
        tol_manipulability : minimum manipulability threshold to consider the solution valid (optional)
        q_min : (n,) minimum joint limits (optional)
        q_max : (n,) maximum joint limits (optional)
        objective_func : function that takes (n,) theta and returns a scalar value (optional)
        objective_args : dictionary of additional arguments to pass to objective_func (optional)
        k_null : weight for the null-space objective (default: 0.1)
        k_damping : damping factor for damped least squares inverse (default: 0.01)
        print_iterations : whether to print iteration details (optional)

    Returns:
        theta : (n,) solution joint coordinates
        theta_history : (max_iters+1, n) history of joint coordinates during iterations
    """
    theta = np.asarray(theta_init, dtype=float).reshape(-1)
    p_des = np.asarray(p_des, dtype=float).reshape(3)

    theta_history = [theta.copy()]

    for i in range(max_iters):

        T_ee = body_product_of_exponentials(M_ee, B_list, theta)
        p_ee = T_ee[:3, 3]

        error = p_des - p_ee

        if print_iterations:
            theta_str = ", ".join(
                f"θ{j+1}={np.degrees(t):.2f}°" for j, t in enumerate(theta)
            )
            print(
                f"Iteration {i}: ({theta_str}), "
                f"(x,y,z)=({p_ee[0]:.3f}, {p_ee[1]:.3f}, {p_ee[2]:.3f}), "
                f"||error||={np.linalg.norm(error):.3e}"
            )

        if np.linalg.norm(error) < tol_converge:
            break

        J_b = body_jacobian(B_list, theta)
        J_v = J_b[3:, :]
        dq = J_v.T @ K @ error

        theta = theta + dq
        if q_min is not None and q_max is not None:
            theta = np.clip(theta, q_min, q_max)

        theta_history.append(theta.copy())

    return theta, np.array(theta_history)
